### ISSUE TITLE
Return new keys in json or xml format

### ISSUE THREAD

**Issue by cadayton** [cyphercosmo/nostr-keys-generator#1]
It would be useful if the cli would just return the new keys in json or xml format.

This would make the code easier to integrate with other code without having to parse threw raw text data which is currently returned.

**Comment by cyphercosmo** [comment]
Makes sense @cadayton , will work on it 🫡

**Comment by cyphercosmo** [comment]
It's now implemented @cadayton 😉

**Comment by cadayton** [comment]
Thank you @cyphercosmo.

The json option returns a string array in PowerShell but I can easily extract the json by referencing the index range of 4..7.

Example:
PS> Get-NewNostrKeys -json

publicKey                                                            privateKey
---------                                                            ----------
npubbf3501d2f80299081e521fecef377881cbacab1a001b26e7693fa236aa81092d nsec07a0f50e5464cd6939dc94e8423791dd9c5f…

If interested the Powershell code can be download here.
https://codeberg.org/cadayton/NewNostrKeys.git
